[build]
  publish = ".next"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
